# Generated by Django 3.2.18 on 2023-04-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_category'),
        ('todo', '0006_todo_activity_type'),
    ]

    operations = [
    ]
