import React from "react";

export const PRIMARY="#0E123F";
export const SECONDARY="#AF91E9";
export const API_URL="http://127.0.0.1:8000/";
export const DialogContext = React.createContext();

export const indoorActivities = {
  read:'',
  reading:'',
  study:'',
  studying:'',
  meet:'',
  meeting:'',
  cook:'',
  cooking:'',
  breakfast:'',
  brunch:'',
  lunch:'',
  dinner:'',
  snack:'',
  nap:'',
  sleep:'',
  dream:'',
  write:'',
  writing:'',
  draw:'',
  drawing:'',
  paint:'',
  painting:'',
  knit:'',
  knitting:'',
  crochet:'',
  crocheting:'',
  sew:'',
  sewing:'',
  craft:'',
  crafting:'',
  DIY:'',
  dance:'',
  singing:'',
  music:'',
  play:'',
  gaming:'',
  video_game:'',
  board_game:'',
  puzzle:'',
  movie:'',
  TV:'',
  documentary:'',
  meditation:'',
  yoga:'',
  workout:'',
  fitness:'',
  exercise:'',
  gym:'',
  run:'',
  jogging:'',
  walk:'',
  hiking:'',
  bike:'',
  cycling:'',
  stretch:'',
  relaxation:'',
  spa:'',
  massage:'',
  aromatherapy:'',
  skincare:'',
  makeup:'',
  haircare:'',
  cleaning:'',
  declutter:'',
  organize:'',
  decorate:'',
  browse:'',
  shopping:'',
  online_shop:'',
  social_media:'',
  chat:'',
  video_call:'',
  learn:'',
  education:'',
  course:'',
  certification:'',
  skillshare:'',
  udemy:'',
  youtube:'',
  podcast:'',
  audiobook:'',
  language:'',
  travel:'',
  plan_trip:'',
  research:'',
  browse_map:'',
  virtual_tour:'',
  museum:'',
  art_gallery:'',
  zoo:'',
  aquarium:'',
  botanic_garden:'',
  library:'',
  park:'',
  planetarium:'',
  science_center:'',
  history:'',
  architecture:'',
  photography:'',
  videography:'',
  pet_care:'',
  volunteer:'',
  donate:'',
  write_letter:'',
  call:'',
  email:'',
  catch_up:''
  };

  export const outdoorActivities = {
    ride: '',
    walk: '',
    walking: '',
    hike: '',
    hiking: '',
    trek: '',
    trekking: '',
    jog: '',
    jogging: '',
    run: '',
    running: '',
    sprint: '',
    sprinting: '',
    cycle: '',
    cycling: '',
    swim: '',
    swimming: '',
    dive: '',
    diving: '',
    surf: '',
    surfing: '',
    sail: '',
    sailing: '',
    paddle: '',
    paddling: '',
    row: '',
    rowing: '',
    kayak: '',
    kayaking: '',
    climb: '',
    climbing: '',
    camp: '',
    camping: '',
    hunt: '',
    hunting: '',
    fish: '',
    fishing: '',
    golf: '',
    soccer: '',
    basketball: '',
    volleyball: '',
    rugby: '',
    football: '',
    baseball: '',
    softball: '',
    tennis: '',
    badminton: '',
    frisbee: '',
    skate: '',
    skating: '',
    skateboard: '',
    rollerblade: '',
    rollerblading: '',
    parkour: '',
    adventure: '',
    exploration: '',
    safari: '',
    tour: '',
    travel: '',
    excursion: '',
    trip: '',
    sightsee: '',
    sightseeing: ''
  };

//http://www.accuweather.com/images/weathericons/3.svg

export const weatherData=[
    {
      "DateTime": "2023-04-07T09:00:00-03:00",
      "EpochDateTime": 1680868800,
      "WeatherIcon": 3,
      "IconPhrase": "Partly sunny",
      "HasPrecipitation": false,
      "IsDaylight": true,
      "Temperature": {
        "Value": 38,
        "Unit": "F",
        "UnitType": 18
      },
      "PrecipitationProbability": 15,
      "MobileLink": "http://www.accuweather.com/en/ca/ohio/b2g/hourly-weather-forecast/3388995?day=1&hbhhour=9&lang=en-us",
      "Link": "http://www.accuweather.com/en/ca/ohio/b2g/hourly-weather-forecast/3388995?day=1&hbhhour=9&lang=en-us"
    },
    {
      "DateTime": "2023-04-07T10:00:00-03:00",
      "EpochDateTime": 1680872400,
      "WeatherIcon": 2,
      "IconPhrase": "Mostly sunny",
      "HasPrecipitation": false,
      "IsDaylight": true,
      "Temperature": {
        "Value": 41,
        "Unit": "F",
        "UnitType": 18
      },
      "PrecipitationProbability": 10,
      "MobileLink": "http://www.accuweather.com/en/ca/ohio/b2g/hourly-weather-forecast/3388995?day=1&hbhhour=10&lang=en-us",
      "Link": "http://www.accuweather.com/en/ca/ohio/b2g/hourly-weather-forecast/3388995?day=1&hbhhour=10&lang=en-us"
    },
    {
      "DateTime": "2023-04-07T11:00:00-03:00",
      "EpochDateTime": 1680876000,
      "WeatherIcon": 2,
      "IconPhrase": "Mostly sunny",
      "HasPrecipitation": false,
      "IsDaylight": true,
      "Temperature": {
        "Value": 44,
        "Unit": "F",
        "UnitType": 18
      },
      "PrecipitationProbability": 0,
      "MobileLink": "http://www.accuweather.com/en/ca/ohio/b2g/hourly-weather-forecast/3388995?day=1&hbhhour=11&lang=en-us",
      "Link": "http://www.accuweather.com/en/ca/ohio/b2g/hourly-weather-forecast/3388995?day=1&hbhhour=11&lang=en-us"
    },
    {
      "DateTime": "2023-04-07T12:00:00-03:00",
      "EpochDateTime": 1680879600,
      "WeatherIcon": 1,
      "IconPhrase": "Sunny",
      "HasPrecipitation": false,
      "IsDaylight": true,
      "Temperature": {
        "Value": 48,
        "Unit": "F",
        "UnitType": 18
      },
      "PrecipitationProbability": 0,
      "MobileLink": "http://www.accuweather.com/en/ca/ohio/b2g/hourly-weather-forecast/3388995?day=1&hbhhour=12&lang=en-us",
      "Link": "http://www.accuweather.com/en/ca/ohio/b2g/hourly-weather-forecast/3388995?day=1&hbhhour=12&lang=en-us"
    },
    {
      "DateTime": "2023-04-07T13:00:00-03:00",
      "EpochDateTime": 1680883200,
      "WeatherIcon": 2,
      "IconPhrase": "Mostly sunny",
      "HasPrecipitation": false,
      "IsDaylight": true,
      "Temperature": {
        "Value": 51,
        "Unit": "F",
        "UnitType": 18
      },
      "PrecipitationProbability": 0,
      "MobileLink": "http://www.accuweather.com/en/ca/ohio/b2g/hourly-weather-forecast/3388995?day=1&hbhhour=13&lang=en-us",
      "Link": "http://www.accuweather.com/en/ca/ohio/b2g/hourly-weather-forecast/3388995?day=1&hbhhour=13&lang=en-us"
    },
]